# Generated by Django 5.2.6 on 2026-06-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Clave de sesión anónima del usuario para aislar su historial.', max_length=40)),
                ('input_type', models.CharField(choices=[('text', 'Texto'), ('url', 'Enlace Web'), ('image', 'Captura de Pantalla')], help_text='Estrategia de extracción que se utilizó en la caja inteligente.', max_length=10)),
                ('original_content', models.TextField(help_text='Texto original o extraído (limpio o truncado a 5000 caracteres).')),
                ('verdict', models.CharField(choices=[('CONFIABLE', 'Confiable'), ('DUDOSO', 'Dudoso'), ('PROBABLE DESINFORMACIÓN', 'Probable Desinformación')], help_text='Nivel de credibilidad determinado por el modelo semántico.', max_length=25)),
                ('score', models.IntegerField(help_text='Puntaje numérico de credibilidad en el rango de 0 a 100.')),
                ('explanation', models.TextField(help_text='Justificación analítica en lenguaje comprensible (máximo 120 palabras).', max_length=500)),
                ('snippets_json', models.TextField(default='[]', help_text='Estructura JSON con los fragmentos específicos que activaron las alertas.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta en la que se completó la evaluación.')),
            ],
            options={
                'verbose_name': 'Análisis de Sesión',
                'verbose_name_plural': 'Análisis de Sesiones',
                'ordering': ['-created_at'],
            },
        ),
    ]
