# Generated by Django 5.2.6 on 2026-06-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denofa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionanalysis',
            name='explanation',
            field=models.TextField(help_text='Justificación analítica en lenguaje comprensible (máximo 120 palabras).'),
        ),
    ]
